#------------------------------------------------------------------------------
# FILE NAME:	Makefile
# DESCRIPTION:	Makefile for a C++ program
# PURPOSE:	Build a program executable
# MODIFICATION HISTORY:
# 
# Author	Date		Modification(s)
# -----------   -----------     ---------------
# Chris Reyes   2021-04-20      1.0 Builds matrix_test1
# Chris Reyes   2021-04-20      2.0 Builds matrix_test2
# Chris Reyes   2021-04-20      3.0 Builds matrix_test ver (1-5)
# Chris Reyes   2021-04-29      4.0 Copied from Lab7 to build matrix_math
#------------------------------------------------------------------------------
#
#	This is our original generic makefile command that will build 
# 	any stand alone ".cpp" source file.
#	Usage: e.g., make matrix_math

.cpp :
	g++ -o $* $*.cpp -std=c++11

matrix_math:  Matrix.cpp Matrix.h
matrix_math1: Matrix.cpp Matrix.h
